### ISSUE TITLE
fix stacktrace

### ISSUE THREAD

**Issue by ndmanvar** [sentry-demos/sentry_react_native#37]
Right now it looks "off"

<img width="581" alt="image" src="https://github.com/sentry-demos/sentry_react_native/assets/314061/848f5f6a-3493-4880-86c4-634e0222a37f">
https://testorg-az.sentry.io/issues/3568862458/?project=5716557&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=24h&stream_index=5#exception

<img width="567" alt="image" src="https://github.com/sentry-demos/sentry_react_native/assets/314061/31d7de8f-fb9c-417a-a892-e87e5b68a211">
https://testorg-az.sentry.io/issues/2986510539/?project=5716557&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=24h&stream_index=1#exception

**Comment by ndmanvar** [comment]
this may be fixed via updating sdk?

**Comment by krystofwoldrich** [comment]
Fixed by: https://github.com/sentry-demos/sentry_react_native/pull/35

Error: https://testorg-az.sentry.io/issues/4438316682/events/2096f25014dd4ef8b73342e59dbc74e4/
Release with source maps: https://testorg-az.sentry.io/releases/com.sentry_react_native%40999.0.1%2B17/?project=5716557

![Screenshot 2023-08-30 at 16 16 03](https://github.com/sentry-demos/sentry_react_native/assets/31292499/393e2b06-9f06-428e-99d2-e55c1e77ef32)
